language: java

jdk:
  - openjdk11

git:
  depth: 3

branches:
  only:
    - master
    - feature
    - fix

# Test & Build SpringBoot app
script:
  - ./gradlew test

# If the `script` job fails, it will send a failure message to Teams channel
after_failure:
  - export TITLE="Travis:$TRAVIS_JOB_ID -- build job is failed"
  - export TEXT=[datetime]:`date`

#after_success:
#  - bash <(curl -s https://codecov.io/bash) -t

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
    recipients:
      - andreselias2303@gmail.com
    on_success: always
    on_failure: always