language: java

jdk:
  - openjdk11

git:
  depth: 3

branches:
  only:
    - master
    - feature
    - fix

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn cobertura:cobertura

# Test & Build SpringBoot app
script:
  - mvn test

# If the `script` job fails, it will send a failure message to Teams channel
after_failure:
  - export TITLE="Travis:$TRAVIS_JOB_ID -- build job is failed"
  - export TEXT=[datetime]:`date`

after_success:
  - bash <(curl -s https://codecov.io/bash) -t

notifications:
  email:
    recipients:
      - andreselias2303@gmail.com
    on_success: always
    on_failure: always