INSERT INTO countries (name, code) VALUES ('Spain', 'es')
INSERT INTO countries (name, code) VALUES ('Netherland', 'nl')
INSERT INTO countries (name, code) VALUES ('France', 'fr')
INSERT INTO countries (name, code) VALUES ('Germany', 'de')

INSERT INTO cities (name, id_country) VALUES ('Madrid', 1)
INSERT INTO cities (name, id_country) VALUES ('Barcelona', 1)
INSERT INTO cities (name, id_country) VALUES ('Amsterdam', 2)
INSERT INTO cities (name, id_country) VALUES ('Lyon', 3)
INSERT INTO cities (name, id_country) VALUES ('Berlin', 4)